version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: gravvisoft-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.multi.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
